### ISSUE TITLE
line 144: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SaintPaddy** [mikepitagno/asa_cleanup#1]
Good afternoon,

This looks like  avery interesting script.
Tried it today, but did not get far.
I have the entire output of a "show run" command saved in a text file called "showrun_10.12.10.44.txt".

```
Y:\TEST>asa_cleanup.py showrun_10.12.10.44.txt

  File "Y:\TEST\asa_cleanup.py", line 114
    print "no object network %s" % (i)
                               ^
SyntaxError: invalid syntax
```

This is the Python version I'm using;
`Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32`

Any idea what could be causing this?

**Comment by mikepitagno** [comment]
I've only written / tested this in Python 2.  There are likely several syntactic issues related to differences with Python 3.  If I find some time, I'll try to create a version compatible with Python 3.

**Comment by SaintPaddy** [comment]
Thank you for pointing me int the right direction with that error. Seeing how it is Sunday and I've got nothing better to do, I gave this a try.
Never used GitHub before, but I hope you found the updated file.

Thank you for this script! Very useful, I could never have created this myself.

**Comment by mikepitagno** [comment]
Thanks!  Glad you found it useful.  I merged your version in after I tested it okay in Python3.  I appreciate the help.
